# Site settings
title: Yasutoshi blog
email: 
description: "test"
baseurl: ""
url: "http://yasutoshi.github.io"
twitter_username:
github_username:

# Build settings
markdown: redcarpet
permalink: pretty
